language: python
python:
  - "3.8"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - pytest -s -v
notifications:
  email:
    recipients:
      -maksym.bova@qatestlab.net
    on_success: never
    on_failure: always